sass-lint:
  config_file: .sass-lint.yml
  enabled: true

scss:
  enabled: false

eslint:
  enabled: false

jshint:
  enabled: false

rubocop:
  enabled: false

coffeescript:
  enabled: false

haml:
  enabled: false

fail_on_violations: true
