scss:
  config_file: .stylelintrc.json
  ignore_file: .stylelintignore
  enabled: true

eslint:
  config_file: .eslintrc.js
  ignore_file: .eslintignore
  enabled: true

jshint:
  ignore_file: .jshintignore
  config_file: .jshintrc
  enabled: false

rubocop:
  enabled: false

coffeescript:
  enabled: false

haml:
  enabled: false

fail_on_violations: true
