---
title: House House Designs
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
# email: your-email@domain.com
description: 'House House is a multidisciplinary design practice in Vancouver, Canada
  — a joint production between Ben Groulx and Sean Durfee. You can hire us to help
  you connect with your audience in ways that will enrich their lives. '
baseurl: 
url: http://househouse.design
markdown: kramdown
gems:
- jekyll-coffeescript
- jekyll-watch
- jekyll-assets
- autoprefixer-rails
